name: My First workflow
on: push
jobs:
    first_job:
        #define where the job runs
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
              
            - name: List and Read file
              run: |
                   echo "My first Github job"
                   ls -ltra
                   cat README.md
            - name: send slack notification
              uses: slackapi/slack-github-actions@v1.24.0
              with:
                payload: |
                         {
                         "text":"Build on *{{ github.repository}}* has *${{job.status}}*.\n '${{github.sha}}' by ${{github.actor}}"
                          }
                env:
                  SLACK_WEBHOOK_URL: ${{secrets.SLACK_WEBHOOK_URL}}

           # - name: Generate ASCII Artwork
            #  run:  cowsay -f dragon "Run for cover, I am a DRAGON.....RAWR">>dragon.txt
            
            #- name: List files
            #  run: ls

            #- name: Read files
            # run: cat  practice.txt

