name: My First workflow

on: push

jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Build
        run: echo "Building completed"

  notify:
    needs: first_job   # ensures this runs after first_job
    runs-on: ubuntu-latest
    steps:
      - name: Send simple message to Slack
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{\"text\":\"🚀 A push was made to the main branch of ${{ github.repository }} by ${{ github.actor }}.\"}" \
          $SLACK_WEBHOOK_URL

           

    

