name: Generate Ascii
on: push
jobs:
    first_job:
        #define where the job runs
        runs-on: ubuntu-latest
        steps:
            - name: Checkout Repo
              uses: actions/checkout@v4
              
            - name: List files
              run: ls -ltra

            - name: Executing shell script
              run: |
                    chmod +x ascii-script.sh
                    ./ascii-script.sh

            #- name: List files
            #  run: ls

            #- name: Read files
            # run: cat  practice.txt

