name: Generate ASCII Network

on:
    push

jobs:
    build_job_1:
        runs-on: ubuntu-latest
        steps:
        - name: Install Cowsay Program
          run: sudo apt-get install cowsay -y

        - name: Execute Cowsat CMD
          run: cowsay -f dragon "Run for cover, I am a Dragon...RAWR">>dragon.txt

        - name: Sleep for 30 seconds
          run: sleep 30

    test_job_2:
        needs: build_job_1    #This job will be executed after the build job
        runs-on: übuntu-latest
        steps:
        - name: Sleep for 10 seconds
          run: sleep 10

        - name: Test File Exists
          run: grep -i "dragon" dragon.txt
    
    deploy_job_1:
        needs: [test_job_2]          # if job depends on more than 1 job then we can make use of array
        runs-on: ubuntu:latest
        steps:
        - name: Read file
          run: cat dragon.txt

        - name: Print
          run: echo "deployment successfull....."
    
          


